server:
  port: 8097
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5444/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true